language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV=test

services:
  - postgresql
  
cache:
  directories:
    - "node_modules"

before_script:
  - "npm run build"
  - psql -c 'DROP DATABASE IF EXISTS travis_ci_test;' -U postgres
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c "CREATE USER johngorithm WITH PASSWORD 'neme7jo@';" -U postgres
  - "npm run migrate"  
scripts:
  - "npm run test:dev"

after_success: "npm run coverage"

 